### ISSUE TITLE
NotFound, message: "No such file or directory"

### ISSUE THREAD

**Issue by PaulRBerg** [leanthebean/puzzle-hunt#1]
This might be a Docker-related problem, but it happens after running `~/zokrates compile -i addToTen.code`:

```
Compiling addToTen.code
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I solved it, but I posted the issue if someone else stumbles upon on it. The key is that you have to provide the absolute path of the folder on your machine. For instance:

`docker run -v zokrates:/home/zokrates/code`

Will **NOT** work. You have to do this:

`docker run -v /Users/you/zokrates:/home/zokrates/code`

**Comment by MdRasheedAhmed** [comment]
> This might be a Docker-related problem, but it happens after running `~/zokrates compile -i addToTen.code`:
> 
> ```
> Compiling addToTen.code
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> ```
> 
> I solved it, but I posted the issue if someone else stumbles upon on it. The key is that you have to provide the absolute path of the folder on your machine. For instance:
> 
> `docker run -v zokrates:/home/zokrates/code`
> 
> Will **NOT** work. You have to do this:
> 
> `docker run -v /Users/you/zokrates:/home/zokrates/code`

This worked for me. Also to if your path has spaces and uppercase try using "$(pwd)". Hope this resolves.
